name: Deploy GitHub Pages

# 触发条件：在 push 到 master 分支后
on:
  push:
    branches:
      - master

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # 生成静态文件
      - name: Build
        run: yarn && yarn docs:build

      # 部署到 GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/.vuepress/dist
      # - name: 同步代码到码云
      #   uses: wei/git-sync@v1
      #   env:
      #     SOURCE_REPO: "git@github.com:x-vic/code.git"
      #     SOURCE_BRANCH: "refs/remotes/source/*"
      #     DESTINATION_REPO: "git@gitee.com:x-vic/code.git"
      #     DESTINATION_BRANCH: "refs/heads/*"
      #     # SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #     SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      #   with:
      #     args: $SOURCE_REPO $SOURCE_BRANCH $DESTINATION_REPO $DESTINATION_BRANCH
      # # 码云点击部署
      # - name: 码云 pages 部署
      #   run: npm run deploy ${{ secrets.GITEE_NAME }} ${{ secrets.GITEE_PWD }}


      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: "git@github.com:x-vic/code.git"
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: "git@gitee.com:x-vic/code.git"

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@master
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: 18373209286
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PWD }}
          # 注意替换为你的 Gitee 仓库
          gitee-repo: x-vic/code
          branch: gh-pages